version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#schedule-
    schedule:
      interval: "monthly"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"